/// <reference types="cypress" />

beforeEach(() => {
  cy.visit('http://localhost:3000/')
})

describe('Main search bar', () => {
  it('Typing valid person name and selecting', () => {
    cy.get('.main-search-container')
      .get('input')
      .type('saoirse')
      .should('have.value', 'saoirse')
    cy.get('.result-container').its('length').should('gte', 3)
    cy.get('.main-search-container')
      .get('input')
      .type('{downarrow}{downarrow}{uparrow}{downarrow}')
    cy.get('.result-container')
      .eq(2)
      .find('.sub')
      .should('contain.text', 'Known for:')
    cy.get('.result-container')
      .eq(2)
      .children('.active')
      .should('exist')
      .click()
    cy.get('.results-container').should('not.exist')
    cy.get('.main-search-container').get('input').should('have.value', '')
  })

  it('Typing invalid person search', () => {
    cy.get('.main-search-container')
      .get('.switch')
      .find('.person')
      .should('exist')
    cy.get('.main-search-container')
      .get('input')
      .type('asadasdwaaeasad')
      .get('.placeholder')
      .should('exist')
      .should('have.text', 'Sorry, no results found')
    cy.get('.main-search-container')
      .get('input')
      .type('{selectall}{backspace}')
      .get('.placeholder')
      .should('exist')
      .should('have.text', 'Search for a person in the film industry')
    cy.get('.main-search-container')
      .get('input')
      .blur()
      .get('results-container')
      .should('not.exist')
  })
  it('Typing valid movie title and selecting', () => {
    cy.get('.main-search-container')
      .get('.switch')
      .get('button')
      .eq(2)
      .click()
      .get('.switch')
      .find('.movie')
      .should('exist')
    cy.get('.main-search-container')
      .get('input')
      .click()
      .get('.placeholder')
      .should('exist')
      .should('have.text', 'Search for a movie or series')
    cy.get('.main-search-container')
      .get('input')
      .type('star')
      .should('have.value', 'star')
    cy.get('.result-container').its('length').should('gte', 3)
    cy.get('.main-search-container')
      .get('input')
      .type('{downarrow}{downarrow}{uparrow}{downarrow}')
    cy.get('.result-container').eq(2).children('.active').should('exist')
    cy.get('.result-container')
      .eq(2)
      .find('.sub')
      .should('contain.text', 'Release date:')
    cy.get('.main-search-container')
      .get('input')
      .type('{selectall}{backspace}')
      .should('have.value', '')
    cy.get('.results-container').should('not.exist')
  })
  it('Typing invalid movie search', () => {
    cy.get('.main-search-container').get('.switch').get('button').eq(2).click()
    cy.get('.main-search-container')
      .get('input')
      .type('asadasdwaaeasad')
      .get('.placeholder')
      .should('exist')
      .should('have.text', 'Sorry, no results found')
    cy.get('.main-search-container')
      .get('input')
      .type('{selectall}{backspace}')
      .get('.placeholder')
      .should('exist')
      .should('have.text', 'Search for a movie or series')
    cy.get('.main-search-container')
      .get('input')
      .blur()
      .get('results-container')
      .should('not.exist')
  })
})
