export { default as User } from './User/User.svelte'
export { default as Search } from './Search/Search.svelte'
export { default as Persons } from './Persons/Persons.svelte'
export { default as Movie } from './Movie/Movie.svelte'
export { default as ArrowRight } from './ArrowRight/ArrowRight.svelte'
export { default as Star } from './Star/Star.svelte'
